### ISSUE TITLE
I have a problem with the universal handler "*" when I use routes with parameters

### ISSUE THREAD

**Issue by lolix-kernel** [alexdodonov/mezon-router#11] opened 2021-02-14 02:46 UTC
When I try for example this code:

```bash
$router = new \Mezon\Router\Router();
$router->addRoute('/hello/[a:name]', function($route, $parameters) {
    $name = $parameters['name'];
    echo "hello $name";
});

$router->addRoute('/*/', function() {
    echo "example text";
});

$router->callRoute($_SERVER['REQUEST_URI']);
```

And when I navigate to the route '/hello/world' I see the output for the universal handler "example text". I don't know if maybe I have a problem or error in my code. The thing I want it's create a website and the routes differents for my defined routes show a message or alert.

**Comment by sinakuhestani** [comment] 2021-02-14 10:59
I have a similar issue! In my case, 
`$this -> addRoute( '/pages/[s:test]/' , function(){echo "OK";} );`
Works only for "/pages/s/"

**Comment by sinakuhestani** [comment] 2021-02-14 11:25
I think the problem is with addParamRoute Method of RoutesSet Tarit. 
`$this->paramRoutes[$requestMethod][$bunchCursor]['bunch'][$lastBunchSize + 1] = [
            'pattern' => $route,
            'callback' => $callback
        ];`
above part of your code sets $route in regex pattern while [s:test] is not a regex pattern for "any string";

**Comment by sinakuhestani** [comment] 2021-02-14 12:50
> When I try for example this code:
> 
> ```shell
> $router = new \Mezon\Router\Router();
> $router->addRoute('/hello/[a:name]', function($route, $parameters) {
>     $name = $parameters['name'];
>     echo "hello $name";
> });
> 
> $router->addRoute('/*/', function() {
>     echo "example text";
> });
> 
> $router->callRoute($_SERVER['REQUEST_URI']);
> ```
> 
> And when I navigate to the route '/hello/world' I see the output for the universal handler "example text". I don't know if maybe I have a problem or error in my code. The thing I want it's create a website and the routes differents for my defined routes show a message or alert.

This is because /*/ is considered to be static and overrides all dynamic roles while it must be considered dynamic.

**Comment by lolix-kernel** [comment] 2021-02-14 19:57
How can I fix the error, please?
And thanks for getting back to me.

**Comment by alexdodonov** [comment] 2021-02-15 16:04
@lolix-kernel Hi! "*" route overrides all routes.

Looks like you have expected that it works in this way:

```php
$router->addRoute('/hello/[a:name]', ...); // 1st
$router->addRoute('*', ...); // 2nd
$router->addRoute('/buy/[a:name]', ...); // 3rd

// for route /hello/joe/ will be called the first route
// for route /some-unexpected-route/ will be called the second route
// for route /buy/helen/ will be also called the second route
```

Am I right?

**Comment by alexdodonov** [comment] 2021-02-15 17:05
@lolix-kernel try version 1.3.0

I hope it will fix all your issues

**Comment by alexdodonov** [comment] 2021-02-15 17:17
@sinakuhestani 

> I have a similar issue! In my case,
> `$this -> addRoute( '/pages/[s:test]/' , function(){echo "OK";} );`
> Works only for "/pages/s/"

Could you please explain what do you mean?

This code works fine:

```php
$router = new Router();
$router->addRoute('/pages/[s:test]/', function (string $route, array $params) {
       return $params['test'];
});

// test body
var_dump($router->callRoute('/pages/s/')); // outputs 's'
var_dump($router->callRoute('/pages/t/')); // outputs 't'
var_dump($router->callRoute('/pages/sssss/')); // outputs 'sssss'
var_dump($router->callRoute('/pages/1/')); // outputs '1'
```

**Comment by lolix-kernel** [comment] 2021-02-15 21:37
> @lolix-kernel try version 1.3.0
> 
> I hope it will fix all your issues

I tried the new version of the router and now my code works, thank you so much.

**Comment by alexdodonov** [comment] 2021-02-16 05:38
Hi! You can use `$router->setNoProcessorFoundErrorHandler(function(string $route){echo "Error 404";});` for processing error if route handler was not found.

**Comment by lolix-kernel** [comment] 2021-02-16 21:06
Thanks again, now I use the method that you said me:
```PHP
$router->setNoProcessorFoundErrorHandler(function(string $route){echo "Error 404";}); 
```

Thank you so much again

**Comment by alexdodonov** [comment] 2021-02-17 04:42
Looks like I can close this issue.

If you have another problems - feel free to open new ones.

**Closed by alexdodonov** 2021-02-17 04:42 UTC
